version: "3.5"

networks:
  ouroboros:

services:
  ouroboros:
    # -u: allow self update
    command: -u
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    #image: ${image_provider:-scififarms}/technocore-ouroboros:${TAG:-latest}
    image: pyouroboros/ouroboros:latest
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - ouroboros
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
