version: "3.5"

networks:
  ouroboros:

services:
  ouroboros:
    # -u: allow self update
    command: --self-update --swarm --label-enable --labels-only
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - com.ouroboros.enable=true
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    #image: ${image_provider:-scififarms}/technocore-ouroboros:${TAG:-latest}
    image: pyouroboros/ouroboros:latest
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    networks:
      - ouroboros
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ouroboros-technocore:
    command: >
      bash -c "deploy && 
        echo 'Finished deploy, sleeping until service is updated/restarted.' &&
        mkfifo pipe && cat pipe"
    deploy:
      mode: global
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
      labels:
        - com.ouroboros.enable=true
      # Big services will need this modified or removed.
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    environment:
      - SERVER_HOSTNAME=${SERVER_HOSTNAME}
      - HOST_SERVICES_DIR=${TECHNOCORE_SERVICES}
      - TECHNOCORE_ROOT=${TECHNOCORE_ROOT}
    image: ${image_provider:-scififarms}/technocore:${TAG:-latest}
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${TECHNOCORE_ROOT}/.env:/var/lib/technocore/.env"
      - ${DEV_MOUNT_OUROBORS_SERVICES:-$EMPTY_MOUNT}
